version: '3.4'

services:
  postgresqlexpressbatch:
    image: postgresqlexpressbatch
    build:
      context: backend/postgresql-express-batch
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5004:5004
      - 5432:5432
