version: '3.4'

services:
- angularstarter:
    image: angularstarter
    build:
      context: infra/frontend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
      
- postgresqlexpressinfra:
    image: postgresqlexpressinfra
    build:
      context: infra/postgresql/
      dockerfile: ./Dockerfile
    environment:
      POSTGRES_PASSWORD: Trustno1
    container_name: mypostgresqldb
    ports:
      - 5004:5004
      - 5432:5432


# TEST COMMANDS ---------------------------- BEGIN

# sudo docker-compose up --build
# sudo docker container ps
# sudo docker container kill mypostgresqldb

# TEST COMMANDS ---------------------------- END

