# Stage 1: Compile and Build angular codebase

# Use official node image as the base image
FROM node:latest 
# as build

# Set the working directory
WORKDIR /usr/local/app

# Install app dependencies
COPY package.json .
RUN npm install

# Add the Bundle app source code to app folder
COPY . .

# Install all the dependencies
# RUN npm install

# Generate the build of the application
RUN npm run build:ssr
# Stroke up the bootstrap server
RUN npm run ignite:ssr
# Expose the https listening port
EXPOSE 4000

# USER node
CMD ["npm run", "serve:ssr"]
# CMD ["node", "dist/angular-starter/server/main.js"]
