apiVersion: apps/v1
kind: Deployment
metadata:
  name: at-ng-app12ui-frontend
  labels:
    app: at-ng-app12ui
spec:
  selector:
    matchLabels:
      app: at-ng-app12ui
      tags: 1.0.0.0
  replicas: 3
  template:
    metadata:
      labels:
        app: at-ng-app12ui
        tags: 1.0.0.0
    spec:
      containers:
      - name: at-ng-app12ui
        image: docker.io/amtayaji/at-ng-app12ui:1.0.0.0
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: env
        - name: REDIS_SLAVE_SERVICE_HOST
          value: redis-replica
        ports:
        - containerPort: 4000